language: node_js
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
cache:
  directories:
    - "node_modules"
  yarn: true
env:
  global:
    - CXX=g++-4.8
  matrix:
    - NPM_VERSION=2
    - NPM_VERSION=3
    - NPM_VERSION=4
    - NPM_VERSION=5
    - NPM_VERSION=next
matrix:
  fast_finish: true
  allow_failures:
    - env: NPM_VERSION=next
    - node_js: "node"
node_js:
  - "4"
  - "6"
  - "8"
  - "node"
before_install:
  - npm install --global npm@${NPM_VERSION}
after_success:
  - cat ./coverage/lcov.info | node $(npm bin)/coveralls
